name: Push Swagger to Central Repo

on:
  push:
    branches:
      - main
    types:
      - merged

env:
  CENTRAL_REPO: "alexanderritik-central-swagger-repository"
  MICROSERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  push-swagger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Microservice Repository
      uses: actions/checkout@v3

    - name: Clone Central Swagger Repository
      uses: repo-sync/github-sync@v3.5
      with:
        source_repo: ${{ env.CENTRAL_REPO }}
        source_branch: main
        destination: central-repo
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy Swagger File
      run: |
        mkdir -p central-repo/microservices/${{ env.MICROSERVICE_NAME }}
        cp openapi.json central-repo/microservices/${{ env.MICROSERVICE_NAME }}/openapi.json

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update Swagger for ${{ env.MICROSERVICE_NAME }} [Automated]"
        branch: main
        file_pattern: |
          central-repo/microservices/${{ env.MICROSERVICE_NAME }}/openapi.json
